apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
    {{- if .Values.tls.enabled }}
    - name: https
      port: 8443
      targetPort: 8443
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.httpsNodePort }}
      {{- end }}
    {{- end }}
