---
# apps/crapi/certificate-tls.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crapi-tls
  namespace: ${NS}
spec:
  secretName: crapi-tls
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
  dnsNames:
    - ${CRAPI_HOST}
    - crapi.${LAB_DOMAIN}
  ipAddresses:
    - ${LAB_HOST_IP}
